### ISSUE TITLE
Rethink relationships

### ISSUE THREAD

**Issue by thelinuxlich** [rel-js/rel#20]
The Graphback annotations don't make justice to the potential a graph database has. We should think about a @relation annotation suited to RedisGraph strengths.

**Comment by thelinuxlich** [comment]
By looking at what Prisma and neo4j-graphql are doing, I think we can investigate the possibility of implicit relationships, therefore removing relationship annotations(at least for the common use cases, 1-1, 1-N, N-N)

**Comment by ian** [comment]
We can take relationships one step further than the others and support polymorphism (or at least plan for it syntactically).

[prisma](https://www.prisma.io/docs/concepts/components/prisma-schema/relations)

```
model User {
  posts Post[]
}

model Post {
  author   User @relation(fields: [authorId], references: [id])
  authorId Int // relation scalar field  (used in the `@relation` attribute above)
}
```

I'm not a fan of specifying the FK and the relation name, the framework should be able to infer this.

[neo4j-graphql](https://neo4j.com/developer/graphql/)

```
type Movie {
  actors: [Person] @relationship(type: "ACTED_IN", direction: IN)
}

type Person {
  movies: [Movie] @relationship(type: "ACTED_IN", direction: OUT)
}
```

This is much cleaner, I like the mindset of "labeled relations" rather than trying to figure out where the foreign key should go.

We could support polymorphism by using GQL unions:

```
union Favorite = Person | Place | Thing

type Person {
    favorites: [Favorite] @relationship(type: "FAVORITED", direction: OUT)
}
```

This has sorta been the holy grail of GraphQL, trying to make easy unions / polymorphism work.

**Comment by thelinuxlich** [comment]
After studying the behavior of similar projects like DGraph, neo4j-graphql and Prisma I formatted a proposal.

Consider the following schema with two entities related:

```graphql
type User {
   name: String!
   posts: [Post] @relation(type: "AUTHORED", direction: OUT)
}

type Post {
   text: String!
   author: User! @relation(type: "AUTHORED", direction: IN)
}
```

When Rel detects the usage of the @relation directive, it should generate the following mutations + inputs:

```graphql
type Mutation {
  createUser(input: CreateUserInput!): User
  updateUser(input: MutateUserInput!): User
  updateUsers(filter: UserFilter, input: MutateUserInput!): UserMutationResultList
  deleteUser(_id: ID!): User
  deleteUsers(filter: UserFilter): UserMutationResultList
  createPost(input: CreatePostInput!): Post
  updatePost(input: MutatePostInput!): Post
  updatePosts(filter: PostFilter, input: MutatePostInput!): PostMutationResultList
  deletePost(_id: ID!): Post
  deletePosts(filter: PostFilter): PostMutationResultList
  connectPostAuthoredUser(_id: ID!, user: ID!): UserMutationResultList 
  disconnectPostAuthoredUser(_id: ID!, user: ID!): UserMutationResultList
  connectUserAuthoredPost(_id: ID!, filter: PostFilter): PostMutationResultList 
  disconnectUserAuthoredPost(_id: ID!, filter: PostFilter): PostMutationResultList
}
```
For the User that has many Posts:

```graphql
input CreatePostRelationInput {
  title: String!
}
input CreateUserInput {
  name: String!
  posts: [CreatePostRelationInput]
}
```

For the Post that belongs to a User:

```graphql
input CreatePostInput {
  title: String!
  author: ID!
}
```

### Create rules

- You can create a new User and add new Posts to its array, if you want to associate it with existing Posts, you can use the Connect Mutation
- On the other side, a Post can be created associating with a preexisting User(thus passing only the `_id`)

For Update:

```graphql
input MutatePostInput {
  title: String
  author: ID
  _id: ID
}
input MutatePostRelationInput {
  title: String
}
input MutateUserInput {
  name: String
  posts: [MutatePostRelationInput]
  _id: ID
}
```

### Update rules

- For the User, if a posts array is passed, it will work like a merge, updating the posts collection with newly created Posts. Again, if the User wants to associate with preexisting Posts, it should use the Connect Mutation

- For the Post, if it wants to change the User it belongs to, it should use a existing `_id`, otherwise it will throw an error.

### Delete rules

- A User can only be deleted if it doesn't have any Posts attached to it. Otherwise it will throw an error, similar behavior to foreign key constraints in traditional RDBMS.


### Connect/Disconnect Rules

- The Mutation for Connect/Disconnect will have a filter if it's a One-To-Many or Many-to-Many relation and only a entity: ID! if it's a Belongs-to relation
- Connect for a Belongs-to relation will overwrite the existing relation and will throw an error if the entity doesn't exist
- Disconnect can throw a error for a Belongs-to relation if the relation is required(thus, you should use Connect)

### Queries

```graphql
type Query {
  getUser(_id: ID!): User
  findUsers(filter: UserFilter, page: PageRequest, orderBy: [UserOrderByInput]): UserResultList!
  getPost(_id: ID!): Post
  findPosts(filter: PostFilter, page: PageRequest, orderBy: [PostOrderByInput]): PostResultList!
}

input UserFilter {
  name: StringInput
  posts: PostFilter
  _id: IDInput
  and: [UserFilter!]
  or: [UserFilter!]
  not: UserFilter
  createdAt: TimestampInput
  updatedAt: TimestampInput
}

input PostFilter {
  title: StringInput
  author: UserFilter
  _id: IDInput
  and: [PostFilter!]
  or: [PostFilter!]
  not: PostFilter
  createdAt: TimestampInput
  updatedAt: TimestampInput
}

type PostResultList {
  items: [Post]!
  offset: Int
  limit: Int
  count: Int
}

type UserResultList {
  items: [User]!
  offset: Int
  limit: Int
  count: Int
}
```

Looking at the Inputs generated you can see we will be able to query related entities and return these nested fields.

Example: Return the user named "John Doe" and its posts whose title has the word "Climate":

```graphql
query {
  findUsers(filter: { name : { eq: "John Doe"}, posts: { title: { contains: "Climate"}}}) {
      _id
      name
      posts {
          _id
          title 
      }    
  }
}
```
