### ISSUE TITLE
Computed/Calculated/Derived fields

### ISSUE THREAD

**Issue by thelinuxlich** [rel-js/rel#27]
A @lambda annotation would allow a transient and derived field available only on queries:

```graphql
"""@model"""
type User {
  id: ID!
  name: String!
  lastName: String!
  """@lambda"""
  fullName: String!
}
```

Then Rel would scan at startup a lambda folder and use fullName.js to derive the field on queries:

```js
// fullName.js

export default (entity) => entity.name + " " + entity.lastName
```

**Comment by thelinuxlich** [comment]
Reference: https://dgraph.io/docs/graphql/lambda/overview/

**Comment by ian** [comment]
@thelinuxlich I 💯 agree we need really precise API extensibility, almost surgical. 

For me, I'm not sure I prefer annotation in this case - I'd personally rather rely on a directory structure / exports standard that provided extensibility around field granularity:

Here's two scenarios I came up with:

Option 1: 
We use a 1-1 mapping between GQL types and named files in the rel/models directory, and each model file will define it's own default export similar in fashion to how next.js handles it's `pages`
```
./rel
│
└── models
    ├── ...
    └── User.ts
```

```
// rel/models/Post.ts

export default function Post(obj, args, context) {
  return { 
     ...obj,
     fullName: [obj.firstName, obj.lastName].join(' '),
     lazyField: (obj, args, context) => "I'm only run if the query asks for this field"
  }
}
```

Option 2: 
We just assume that only overridden fields will exist as files:
```
./rel
│
└── models
    ├── ...
    └── User/
        └── fullName.ts
```

```
// rel/models/Post/fullName.ts

export default (obj, args, context)  => [obj.firstName, obj.lastName].join(' ')
```

To me this feels much more idiomatic to what a JavaScript developer would expect from their framework.

**Comment by thelinuxlich** [comment]
we could do this automatic inference from the directory structure, but I feel it unnecessarily ties a simple function to a fixed convention(models/x/derivedFieldName.ts), my suggestion allows the user to immediately know which fields are computed(because of the annotation) and reuse the function wherever he wants(just lambdas/fullName.ts).

**Comment by ian** [comment]
Gotcha - why `@lambda` and not `@resolver path/to/resolver.ts`. 

We might want to take inspiration from the SPARQL in specifying the resource that is handling the resolution?

**Comment by thelinuxlich** [comment]
Because when the user sees @lambda it can immediately think of a closure, pure function. It's not really a @resolver, we aren't passing resolver parameters unless there is a specific need for that.
I thought of the user passing the function name and extra arguments as optional parameters in case he don't want Rel to infer the name of the function from the field:

```graphql
This will look for a function in a file named fullName.js in the lambdas folder:

"""@lambda"""
fullName: String!
"""


This will use the name attribute, thus lambdas/formatName.js and pass extra parameters to the function

"""@lambda(name: "formatName", args: ["fancy"])
fullName: String!
````

**Comment by thelinuxlich** [comment]
Added in 3639f09

It's a simpler implementation than what was discussed here, basically running the computed value against Lodash template function, let's see if it demands something more in the future.

This feature doesn't support returning computed values on DELETE mutation due to a missing feature in RedisGraph(properties()) and can't be used with aggregations.
