### ISSUE TITLE
Auto-generate GQL client

### ISSUE THREAD

**Issue by ian** [rel-js/rel#3]
Let's include an auto-generated client library to be regenerated anytime the schema changes.

Options:
- GenQL
- Zeus
- others?

**Comment by thelinuxlich** [comment]
I think we should settle with GenQL, seems more friendly than Zeus, although Zeus supports aliases.

**Comment by ian** [comment]
@thelinuxlich is this done? I saw it moved on the board.

**Comment by thelinuxlich** [comment]
Aren't we already autogenerating the client in the gql-client folder?

**Comment by ian** [comment]
Ah I see now - we're probably gonna want to do a second round on this to make sure DX is right. 

Also, we're gonna want to think about the experience of using this in a project, what does that look like? Would be really great if we could generate this in a way that the integrating framework can tree shake it and not load the rel.server package and deps. Prisma does a good job of this currently.

Example:
```typescript
import { useQuery } from "rel.client"

export default MyComponent(props) {
  const { data, loading } = useQuery({
    getThings: [
      ...
    ]
  })
}
```

**Comment by thelinuxlich** [comment]
The generated client should be on a folder in the user project, so he can inspect what Rel generated, not inside node_modules. I think it's okay for the user to require the local generated file by path.

**Comment by thelinuxlich** [comment]
By the way, what drove us away from GQTY?

**Comment by ian** [comment]
The way I've seen this done well is that you generate it to `node_modules/rel.client/.gen` folder and the `node_modules/rel.client/index.js` does a `require(__DIRNAME + "/.gen/index.js")` and exports it. Keeps the dependencies to a minimum for the client.

**Comment by thelinuxlich** [comment]
rel-cli is generating the GQL client in `/rel/gen/gql-client` so I think this can be closed
