### ISSUE TITLE
Aggregations

### ISSUE THREAD

**Issue by ian** [rel-js/rel#4]
Comparisons:

- https://neo4j.com/developer-blog/neo4j-graphql-aggregations/
- https://dgraph.io/docs/graphql/queries/aggregate/
- https://hasura.io/docs/latest/graphql/core/databases/postgres/queries/aggregation-queries.html
- https://www.graphqlize.org/docs/queries/query-relationships

**Comment by thelinuxlich** [comment]
Just copy-pasting the discussion related to this issue:

thelinuxlich — We will group automatically if the user  adds in the graphql query additional fields besides the common aggregations
```graphql
query {
  findNotes {
    text
    count(of: NoteFields.id)
  }
}
```
Will automatically group by text, count(id)
by the way, if the user calls the aggregation without parameter, should aggregate by id

ih — not sure I follow the last part
everything else sounds right to me 

thelinuxlich — 
```graphql
query {
  findNotes {
    text
    count
  }
}
```
count will be count(id)

ih — yeah sounds right to me

thelinuxlich — ok

**Comment by thelinuxlich** [comment]
Just added the 5 essential aggregations to Rel: (count, max, sum, avg and min). 

The codegen will generate a enum containing all fields of each model to input on count, and a enum containing all fields of number type(including scalars) for the other 4 aggregations.

If the user pass additional fields on query, Rel will automatically GROUP the result, example:

```graphql
Query {
   findTodos(filter: { a: { gt: 1 } }) {
      a
      sum(of: b)
   }
}
``` 
Is equivalent to GROUP(a, sum(b))
