### ISSUE TITLE
CLI

### ISSUE THREAD

**Issue by ian** [rel-js/rel#6]
At some point we want to invest in our CLI tooling.

TODO:

- [x] rel init or npx create-rel-app  whichever feels better
- [x] rel dev

**Comment by ian** [comment]
I really like how react-blessed can produce high-quality local dashboards:

![demo](https://user-images.githubusercontent.com/19853/147502238-4c9b4b37-5dc8-4263-99aa-58daeb8103ab.gif)

**Comment by thelinuxlich** [comment]
This react-blessed thing scares me lol!

**Comment by thelinuxlich** [comment]
I mean, I hope there are already builtin templates

**Comment by ian** [comment]
lol - just dumping ideas in here.

**Comment by ian** [comment]
It's all react based IIRC

**Comment by thelinuxlich** [comment]
Also for reference:

http://yargs.js.org/
https://github.com/enquirer/enquirer

**Comment by ian** [comment]
I believe this is done, closing.
